output_dir: ./data
# for running via the main function
channels_file: /home/cavad/Projects/asr-scraper/channels.txt
sample_rate: 16000
mono: true
pcm_bit_depth: 16
concurrency: 3
max_videos_per_channel: null 
# format: YYYYMMDD (20260219)
since_date: null
skip_existing: true
write_manifest: ./manifest.jsonl